language: go

os:
  - linux
  - osx

go:
- "1.10"

git:
  depth: 3

go_import_path: github.com/kubernetes-sigs/controller-runtime

before_install:
- go get -u github.com/golang/dep/cmd/dep

# Install must be set to prevent default `go get` to run.
# The dependencies have already been vendored by `dep` so
# we don't need to fetch them.
install:
  - go get -u golang.org/x/lint/golint
  - go get -u gopkg.in/alecthomas/gometalinter.v2 && gometalinter.v2 --install

script:
- go vet ./pkg/...
- golint -set_exit_status ./pkg/...
- gometalinter.v2 --disable-all --enable=misspell
- TRACE=1 ./test.sh


# TBD. Suppressing for now.
notifications:
  email: false
