name: Upload binaries to release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

permissions:
  contents: write

jobs:
  build:
    name: Upload binaries to release
    runs-on: ubuntu-latest
    steps:
    - name: Set env
      run:  echo "RELEASE_TAG=${GITHUB_REF:10}" >> $GITHUB_ENV
    - name: Check out code
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # tag=v6.0.2
    - name: Calculate go version
      id: vars
      run: echo "go_version=$(make go-version)" >> $GITHUB_OUTPUT
    - name: Set up Go
      uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # tag=v6.2.0
      with:
        go-version: ${{ steps.vars.outputs.go_version }}
    - name: Generate release binaries
      run: |
        make release
    - name: Release
      uses: softprops/action-gh-release@a06a81a03ee405af7f2048a818ed3f03bbf83c7b # tag=v2.5.0
      with:
        draft: false
        files: tools/setup-envtest/out/*
